# Generated by Django 4.0.2 on 2024-04-15 15:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_rename_seats_cinemahall_seats_in_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesession',
            name='show_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
